from animais import *

def main():
    cachorro = Cachorro("Sid", "Marrom", 2, "Quadrupede", "Pitbull")
    print(cachorro.nome)
    print(cachorro.cor_pelo)
    print(cachorro.idade)
    print(cachorro.tipo_pata)
    print(cachorro.raca)
    print(cachorro.latir())
    print(cachorro.rosnar())
    print(cachorro.correr())
    print(cachorro.mamar())
    print("______________________________________")

    cavalo = Cavalo("BoJack", "Marrom", 40, "Quadrupede", "Preto")
    print(cavalo.nome)
    print(cavalo.cor_pelo)
    print(cavalo.idade)
    print(cavalo.tipo_pata)
    print(cavalo.cor_crina)
    print(cavalo.galopar())
    print(cavalo.relinchar())
    print(cavalo.correr())
    print(cavalo.mamar())
    print("______________________________________")

    gato = Gato("Mimi", "Branco", 1, "Quadrupede")
    print(gato.nome)
    print(gato.cor_pelo)
    print(gato.idade)
    print(gato.tipo_pata)
    print(gato.miar())
    print(gato.morrer())
    print(gato.morrer())
    print(gato.morrer())
    print(gato.morrer())
    print(gato.morrer())
    print(gato.morrer())
    print(gato.morrer())
    print(gato.correr())
    print(gato.mamar())
    print("______________________________________")

    camaleao = Camaleao("Carlaio", "Verde", 5, "Barata")
    print(camaleao.nome)
    print(camaleao.cor)
    print(camaleao.idade)
    print(camaleao.inseto_favorito)
    print(camaleao.tomar_sol())
    print(camaleao.botar_ovo())
    print(camaleao.comer_inseto())
    print(camaleao.mudar_de_cor())
    print("______________________________________")

    cobra = Cobra("Celeste", "Rosa", 10, False)
    print(cobra.nome)
    print(cobra.cor)
    print(cobra.idade)
    print(cobra.veneno)
    print(cobra.tomar_sol())
    print(cobra.trocar_pele())
    print(cobra.rastejar())
    print(cobra.botar_ovo())
    print("______________________________________")

    jacare = Jacare("Juca", "Verde", 2, 40)
    print(jacare.nome)
    print(jacare.cor)
    print(jacare.idade)
    print(jacare.num_dentes)
    print(jacare.tomar_sol())
    print(jacare.botar_ovo())
    print(jacare.atacar())
    print(jacare.dormir())


if __name__ == "__main__":
    main()